### ISSUE TITLE
【监控系统】建议增加grafana项目

### ISSUE THREAD

**Issue by zhongqin0820** [hackstoic/golang-open-source-projects#17]
2013年的项目，[Github 仓库地址：https://github.com/grafana/grafana](https://github.com/grafana/grafana)

Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.

**Comment by hackstoic** [comment]
谢谢建议， 已增加。 欢迎提pull request。
