### ISSUE TITLE
Orivil 是什么鬼

### ISSUE THREAD

**Issue by sunui** [hackstoic/golang-open-source-projects#20]
“Orivil 是由 golang 开发的全新 web 框架”
没有文档、没有官网、两年没有commit？ 由 golang 开发？23 star？

**Comment by hackstoic** [comment]
> “Orivil 是由 golang 开发的全新 web 框架”
> 没有文档、没有官网、两年没有commit？ 由 golang 开发？23 star？

多谢反馈， 已移除该项目。写了个脚本做了自动star数检测和无效链接检测，后期再加入活跃程度的检测，微信文章推荐指数等，确保推荐项目的质量。
