### ISSUE TITLE
部分项目简介错误以及部分项目版本已经被弃用

### ISSUE THREAD

**Issue by Yanwenjiepy** [hackstoic/golang-open-source-projects#36]
1、监控系统， rapidloop/rtop 项目简介，把rtop写成了top;
2、数据库技术  radix.v2 该项目已经弃用，已经迁移至radix, 项目链接为： https://github.com/mediocregopher/radix
3、其他  FishChatServer已弃用，迁移至2.0版本，项目地址：https://github.com/oikomi/FishChatServer2

**Comment by hackstoic** [comment]
已更新。感谢反馈~
