### ISSUE TITLE
ThinkGo项目已更名为Faygo

### ISSUE THREAD

**Issue by henrylee2cn** [hackstoic/golang-open-source-projects#7]
感谢作者的推荐，本人的Pholcus、Lessgo、ThinkGo项目。

由于很多人听到ThinkGO的名字，总是联想到ThinkPHP，进而认为两者设计相同。其实不然。因此已经更名为Faygo。请悉知。

https://github.com/henrylee2cn/faygo

Faygo 是一款快速、简洁的Go Web框架，可用极少的代码开发出高性能的Web应用程序（尤其是API接口）。只需定义 struct Handler，Faygo 就能自动绑定、验证请求参数并生成在线API文档。

**Comment by hackstoic** [comment]
谢谢作者的指正。 已更改过来了。
